### PR TITLE
Add initial log lines

### PR DESCRIPTION
**Pull request by kevinddchen**
@AquaDragon hopefully this helps you get started.

Work towards #103.

### CODE REVIEW

**Comment by AquaDragon** [comment]
Thank

**Comment by AquaDragon** [comment]
you did most the stuff I wanted to do, so we can probably push it

**Comment by kevinddchen** [comment]
Oh lol I cannot approve my own PR. But you can and merge lol.

**Review by AquaDragon — APPROVED** [review]

**Comment by AquaDragon** [comment]
oh lol it was me that had to review and approve it

**Pull request merged**
